name: Terraform Plan

on:
  push:
    branches:
      - 'feature/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'Project 1/Parent Module'

    steps:

      # --------------------------------------------------
      # Checkout Repository
      # --------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # Azure Login using Service Principal
      # --------------------------------------------------
      - name: Azure Login Using Service Principal
        run: |
          az login \
            --service-principal \
            --username "50648d8a-5440-4d4a-93bb-8b9a5f14aaca" \
            --password "kD48Q~RCsCJklAyGJc_gkuV~_2Qz-.t_ZRh._bMr" \
            --tenant "91695fd6-371b-4c10-8dc9-21e31d347ad6"

          az account set \
            --subscription "b299f192-d573-4040-b542-2aff90a974b5"

      # --------------------------------------------------
      # Setup Terraform
      # --------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.2

      # --------------------------------------------------
      # Terraform Init
      # --------------------------------------------------
      - name: Terraform Init
        run: |
          terraform init

      # --------------------------------------------------
      # Terraform Validate
      # --------------------------------------------------
      - name: Terraform Validate
        run: |
          terraform validate

      # --------------------------------------------------
      # Terraform Plan
      # --------------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan